# Generated by Django 3.0.7 on 2020-09-05 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='problem_detail',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('que', models.TextField()),
                ('input1', models.IntegerField()),
                ('input2', models.IntegerField()),
                ('output1', models.CharField(max_length=50)),
                ('output2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='problem_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1000)),
                ('marks', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittion', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('ass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.problem_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
