# Generated by Django 3.1 on 2020-09-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='ass',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.DeleteModel(
            name='problem_detail',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
