# Generated by Django 3.1 on 2020-09-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_auto_20200905_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem_detail',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('que', models.TextField()),
                ('input1', models.CharField(max_length=50)),
                ('input2', models.CharField(max_length=50)),
                ('output1', models.CharField(max_length=50)),
                ('output2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittion', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('ass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.problem_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
