# Generated by Django 3.1 on 2020-09-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_detail_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
