# Generated by Django 3.1 on 2020-09-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='problem_model',
        ),
    ]
