# Generated by Django 3.1 on 2020-09-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_delete_problem_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
