# Generated by Django 3.1 on 2020-09-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
