# Generated by Django 3.0.7 on 2020-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_detail',
            name='difficulty',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem_detail',
            name='info',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='input1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='input2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output2',
            field=models.TextField(max_length=500),
        ),
    ]
