# Generated by Django 3.0.7 on 2020-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20200908_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_detail',
            name='input1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='input2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output2',
            field=models.CharField(max_length=500),
        ),
    ]
