# Generated by Django 3.1 on 2020-09-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20200908_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
