# Generated by Django 3.1 on 2020-09-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_detail',
            name='input1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='input2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output2',
            field=models.TextField(max_length=500),
        ),
    ]
