# Generated by Django 3.1 on 2020-09-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20200912_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_detail',
            name='input1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='input2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_detail',
            name='output2',
            field=models.TextField(),
        ),
    ]
