# Generated by Django 3.0.3 on 2021-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20210817_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='items_name',
            field=models.TextField(blank=True),
        ),
    ]
