# Generated by Django 3.0.3 on 2021-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20210821_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
